server:
  port: 8082
#  servlet:
#    context-path: /eurekaService

spring:
  application:
    name: eureka-service
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    status-page-url: ${server.servlet.context-path}/info
#    health-check-url-path: ${server.servlet.context-path}/health

